fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_prost_build::configure()
        .build_server(false)
        .compile_protos(
            &[
                "invest-contracts/src/docs/contracts/common.proto",
                "invest-contracts/src/docs/contracts/instruments.proto",
                "invest-contracts/src/docs/contracts/marketdata.proto",
                "invest-contracts/src/docs/contracts/operations.proto",
                "invest-contracts/src/docs/contracts/orders.proto",
                "invest-contracts/src/docs/contracts/sandbox.proto",
                "invest-contracts/src/docs/contracts/signals.proto",
                "invest-contracts/src/docs/contracts/stoporders.proto",
                "invest-contracts/src/docs/contracts/users.proto",
            ],
            &["invest-contracts/src/docs/contracts"],
        )?;
    Ok(())
}
